name: 'Kosarev Space Deployment'
description: 'Trigger a Kosarev Space deployment'
branding:
  icon: 'upload-cloud'
  color: 'gray-dark'
inputs:
  auth_token:
    description: 'Kosarev Space authentication token'
    required: true
  service_id:
    description: 'Kosarev Space service ID'
    required: true
runs:
  using: "composite"
  steps:
    - name: Trigger Dokploy deployment
      shell: bash
      env:
        KOSAREV_SPACE_AUTH_TOKEN: ${{ inputs.auth_token }}
        KOSAREV_SPACE_SERVICE_ID: ${{ inputs.service_id }}
      run: |
        response=$(curl -X 'POST' \
          "https://kosarev.space/api/service/$KOSAREV_SPACE_SERVICE_ID/restart" \
          -H 'accept: application/json' \
          -H 'Content-Type: application/json' \
          -H "Authorization: Bearer $KOSAREV_SPACE_AUTH_TOKEN" \
          -w "%{http_code}" \
          -o /dev/null \
          -s)
        
        if [ "$response" -ne 200 ]; then
          echo "Deployment failed with status code: $response"
          exit 1
        fi
